export enum BidStatus {
    CanLapDeNghiDuThau = 'CanLapDeNghiDuThau',
    ChoDuyetDeNghiDuThau = 'ChoDuyetDeNghiDuThau',
    ThamGiaDuThau = 'ThamGiaDuThau',
    TuChoiDuThau = 'DaTuChoi',
    ChuaThongBaoTrienKhai = 'ChuaThongBaoTrienKhai',
    DaThongBaoTrienKhai = 'DaThongBaoTrienKhai',
    DaXacNhanPhanCong = 'DaXacNhanPhanCong',
    DaGuiPhanCongTienDo = 'DaGuiPhanCongTienDo',
    DangLapHSDT = 'DangLapHSDT',
    CanLapTrinhDuyetGia = 'CanLapTrinhDuyetGia',
    DaGuiDuyetTrinhDuyetGia = 'DaGuiDuyetTrinhDuyetGia',
    CanDieuChinhTrinhDuyetGia = 'CanDieuChinhTrinhDuyetGia',
    DaDuyetTrinhDuyetGia = 'DaDuyetTrinhDuyetGia',
    ChotHoSo = 'ChotHoSo',
    DaNopHSDT = 'DaNopHSDT',
    DaNhanLoiMoi = 'DaNhanLoiMoi',
    ChuanBiPhongVan = 'ChuanBiPhongVan',
    DaChotCongTacChuanBiPhongVan = 'DaChotCongTacChuanBiPhongVan',
    DaPhongVan = 'DaPhongVan',
    // KQDT
    TratThau = 'TratThau',
    HuyThau = 'HuyThau',
    DaThongBaoCacBenLienQuan = 'DaThongBaoCacBenLienQuan',
    CoBaiHocKinhNghiem = 'CoBaiHocKinhNghiem',
    TrungThau = 'TrungThau',
    DaPhanHoiDenPHopDong = 'DaPhanHoiDenPHopDong',
    DaKyKetHopDong = 'DaKyKetHopDong',
    DaChuyenGiaoTaiLieu = 'DaChuyenGiaoTaiLieu',
    ChuaNhanTaiLieu = 'ChuaNhanTaiLieu',
    DaNhanTaiLieu = 'DaNhanTaiLieu',
    DaThongBaoHopKickOff = 'DaThongBaoHopKickOff',
    ChuaChuyenGiaoTaiLieu = 'ChuaChuyenGiaoTaiLieu',
}
