export const FakeDocumentAssessment = [
    {
        typeOfDocument: 'Bản vẽ',
        fileName: 'Bản vẽ nền móng & các tầng',
        version: '1.0',
        status: 'Chính thức',
        uploadPeople: 'Hieu Nguyen',
        uploadDate: 1504224000,
    },
    {
        typeOfDocument: 'Cuốn hồ sơ mời thầu',
        fileName: 'Tình trạng hồ sơ mời thầu',
        version: '2.0',
        status: 'Chính thức',
        uploadPeople: 'Huu Nghia',
        uploadDate: 1506816000,
    },
    {
        typeOfDocument: 'Tiêu chuẩn kỹ thuật',
        fileName: 'Tiêu chuẩn theo PLS & QL',
        version: '3.0',
        status: 'Chính thức',
        uploadPeople: 'Hoai An',
        uploadDate: 1504223999,
    },
    {
        typeOfDocument: 'BOQ',
        fileName: 'Kiểm định và thống kế ước lượng giá',
        version: '1.1',
        status: 'Chính thức',
        uploadPeople: 'Quyen Dang',
        uploadDate: 1509494400,
    },
    {
        typeOfDocument: 'khảo sát địa chất',
        fileName: 'Khảo sát địa chất toàn bộ khu vực thi công',
        version: '3.0',
        status: 'Chính thức',
        uploadPeople: 'Huu Uyen',
        uploadDate: 1509494400,
    },
];
