export const FakePackageData = [
    {
        id: 1,
        nameProject: 'Dự án Alma Resort',
        codePackage: '15AR10',
        name: 'Xây dựng',
        task: 'Xây dựng chính',
        address: '156 Phan Châu Trinh',
        zone: {
            id: 5,
            text: 'Nước ngoài',
        },
        quarterOfYear: {
            id: 1,
            text: 'Quý I',
        },
        customer: {
            id: 2,
            text: 'Nguyễn Văn Linh',
        },
        customerType: {
            id: 1,
            text: 'Khách hàng mới',
        },
        contact: {
            id: 4,
            text: 'Trưởng ban kiểm định: Hà Thị Một',
        },
        consultingUnit: 'CP Vật liệu An Giang',
        addressConsultingUnit: '110 Nguyễn Hửu Thọ, Tp.Hồ Chí Minh',
        phoneConsultingUnit: '01229688410',
        trackingeStartDate: 1530403200,
        submitPackageDate: 1535760000,
        expectedResultPackageDate: 1535760000,
        acreageFloor: 50000000,
        scale: '20 tầng',
        buildingProjectType: {
            id: 2,
            text: 'Căn Hộ',
        },
        mainBuildingCategory: {
            id: 3,
            text: 'Xậy dựng móng và mặt bằng',
        },
        roleContractors: {
            id: 1,
            text: 'Chủ đầu tư',
        },
        roleHBC: {
            id: 4,
            text: 'Thầu D&B',
        },
        linkDocument: 'https://vietstock.vn/2018/05/hoa-binh-trung-thau-them-nhieu-du-an-gia-tri-hon-3000-ty-dong-737-606195.htm',
        presideHBC: {
            id: 6,
            text: 'Nguyễn Tiến Dũng',
        },
        status: {
            id: 4,
            text: 'Nộp Lần 1',
        },
        progressMade: null,
        reasonWinPackage: '',
        reasonLostPackage: '',
        totalValue: 8000000000 ,
        // totalTime: 22000000,
        ratingProject: '4',
        // note: 'Dự án cần phải triển khai',
        startDateProject: 1546300800,
        endDateProject: 1551398400,
        totalTimeProject: 20000000,
        description: 'Dự án thuộc khu nghỉ dưỡng cao cấp',
        phase: {
            parent: 'HỒ SƠ DỰ THẦU',
            child: 'Cần đánh giá HSMT',
        }
    },
    {
        id: 2,
        nameProject: 'Xậy dựng nhà ở khu chung cư',
        codePackage: '132CC11',
        name: 'Mua trang thiết bị',
        task: 'Cung cấp vật liệu và giám sát',
        address: '11 Ngô Thì Nhậm',
        zone: {
            id: 1,
            text: 'Miền Bắc',
        },
        quarterOfYear: {
            id: 2,
            text: 'Quý II',
        },
        customer: {
            id: 4,
            text: 'Nguyễn Văn Linh',
        },
        customerType: {
            id: 2,
            text: 'Khách hàng cũ',
        },
        contact: {
            id: 2,
            text: 'Trưởng ban kiểm định: Hà Thị Một',
        },
        consultingUnit: 'CT CP tập đoàn BRG',
        addressConsultingUnit: '121 Tố Hữu, Tp.Nha Trang',
        phoneConsultingUnit: '01698524715',
        trackingeStartDate: 1548979200,
        submitPackageDate: 1551398400,
        expectedResultPackageDate: 1554076800,
        acreageFloor: 40000000,
        scale: '30 tầng',
        buildingProjectType: {
            id: 1,
            text: 'Tổ Hợp',
        },
        mainBuildingCategory: {
            id: 3,
            text: 'Xậy dựng móng và mặt bằng',
        },
        roleContractors: {
            id: 1,
            text: 'Chủ đầu tư',
        },
        roleHBC: {
            id: 2,
            text: 'Tổng thầu',
        },
        linkDocument: 'http://vcci.com.vn/cong-ty-xay-dung-hoa-binh-trung-thau-5-du-an-lon',
        presideHBC: {
            id: 10,
            text: 'Đỗ Quỳnh Loan',
        },
        status: {
            id: 4,
            text: 'Nộp Lần 2',
        },
        progressMade: null,
        reasonWinPackage: '',
        reasonLostPackage: '',
        totalValue: 3000000000,
        // totalTime: 10000000,
        ratingProject: '3',
        // note: 'Dự án đang thực hiện chậm trễ',
        startDateProject: 1556668800,
        endDateProject: 1559347200,
        totalTimeProject: 12000000,
        description: 'Khách sạn',
        phase: {
            parent: 'HỒ SƠ DỰ THẦU',
            child: 'Đã thông báo triển khai',
        }
    },
    {
        id: 3,
        nameProject: 'Khách sạn Biển Đông Phương',
        codePackage: '100BDP',
        name: 'Mua trang thiết bị',
        task: 'Cộng tác thi công',
        address: '02 Nguyễn Đình Phùng',
        zone: {
            id: 2,
            text: 'Miền Trung',
        },
        quarterOfYear: {
            id: 3,
            text: 'Quý III',
        },
        customer: {
            id: 2,
            text: 'Nguyễn Văn Linh',
        },
        customerType: {
            id: 1,
            text: 'Khách hàng mới',
        },
        contact: {
            id: 1,
            text: 'Trưởng ban kiểm định: Hà Thị Một',
        },
        consultingUnit: 'Tập đoàn Xây dựng BBD',
        addressConsultingUnit: '10 Ngô Văn sở,tp Hồ Chí Minh',
        phoneConsultingUnit: '01697864512',
        trackingeStartDate: 1559347200,
        submitPackageDate: 1561939200,
        expectedResultPackageDate: 1564617600,
        acreageFloor: 30000000,
        scale: '10 tầng',
        buildingProjectType: {
            id: 3,
            text: 'Khách Sạn/ Resort',
        },
        mainBuildingCategory: {
            id: 1,
            text: 'Xậy dựng móng và mặt bằng',
        },
        roleContractors: {
            id: 2,
            text: 'Chủ đầu tư',
        },
        roleHBC: {
            id: 4,
            text: 'Thầu D&B',
        },
        linkDocument: 'http://vcci.com.vn/cong-ty-xay-dung-hoa-binh-trung-thau-5-du-an-lon',
        presideHBC: {
            id: 18,
            text: 'Nguyễn Đăng Độ',
        },
        status: {
            id: 4,
            text: 'Nộp Lần 3',
        },
        progressMade: null,
        reasonWinPackage: '',
        reasonLostPackage: '',
        totalValue: 4000000000,
        // totalTime: 20000000,
        ratingProject: '4',
        // note: 'Dự án đang thực hiện',
        startDateProject: 1567296000,
        endDateProject: 1569888000,
        totalTimeProject: 14000000,
        description: 'Chung cư',
        phase: {
            parent: 'KẾT QUẢ DỰ THẦU',
            child: 'Trật thầu',
        }
    },
    {
        id: 4,
        nameProject: 'Giám sát và kiểm định chấy lượng xây dựng Cty HCB02',
        codePackage: '100BDP',
        name: 'Tư vấn xây dựng',
        task: 'Giám sát và kiểm định',
        address: '12 Nguyễn Hùng',
        zone: {
            id: 2,
            text: 'Miền Trung',
        },
        quarterOfYear: {
            id: 2,
            text: 'Quý II',
        },
        customer: {
            id: 2,
            text: 'Nguyễn Văn Linh',
        },
        customerType: {
            id: 1,
            text: 'Khách hàng mới',
        },
        contact: {
            id: 4,
            text: 'Trưởng ban kiểm định: Hà Thị Một',
        },
        consultingUnit: 'Tập đoàn Xây dựng BBD',
        addressConsultingUnit: '23 Ngô Quyền, tp Cần Thơ',
        phoneConsultingUnit: '01223544876',
        trackingeStartDate: 1525132800,
        submitPackageDate: 1527811200,
        expectedResultPackageDate: 1530403200,
        acreageFloor: 40000000,
        scale: '40 tầng',
        buildingProjectType: {
            id: 4,
            text: 'Văn Phòng',
        },
        mainBuildingCategory: {
            id: 2,
            text: 'Xậy dựng móng và mặt bằng',
        },
        roleContractors: {
            id: 2,
            text: 'Chủ đầu tư',
        },
        roleHBC: {
            id: 1,
            text: 'Thầu chính',
        },
        linkDocument: 'http://ndh.vn/su-kien-chung-khoan-dang-chu-y-ngay-6-4-2939769p146c155.news',
        presideHBC: {
            id: 3,
            text: 'Phạm Viết Châu',
        },
        status: {
            id: 4,
            text: 'Nộp Lần 4',
        },
        progressMade: null,
        reasonWinPackage: '',
        reasonLostPackage: '',
        totalValue: 5000000000,
        // totalTime: 30000000,
        ratingProject: '5',
        // note: 'Dự án thiếu nhân viên kiểm định',
        startDateProject: 1533081600,
        endDateProject: 1535760000,
        totalTimeProject: 1538352000,
        description: 'Bệnh viện',
        phase: {
            parent: 'HỒ SƠ DỰ THẦU',
            child: 'Đã gửi thông báo triển khai',
        }
    },
    {
        id: 5,
        nameProject: 'Xây dựng trường THPT Nguyễn Hiền',
        codePackage: '130TH18',
        name: 'Hỗ trợ công trình',
        task: 'Thi công chính',
        address: '523 Nguyễn Hiền',
        zone: {
            id: 2,
            text: 'Miền Trung',
        },
        quarterOfYear: {
            id: 2,
            text: 'Quý II',
        },
        customer: {
            id: 4,
            text: 'Nguyễn Văn Linh',
        },
        customerType: {
            id: 2,
            text: 'Khách hàng cũ',
        },
        contact: {
            id: 1,
            text: 'Trưởng ban kiểm định: Hà Thị Một',
        },
        consultingUnit: 'CT CP đầu tư Việt',
        addressConsultingUnit: '15 Tôn Đản, tp Đà Nẵng',
        phoneConsultingUnit: '01225477884',
        trackingeStartDate: 1541030400,
        submitPackageDate: 1543622400	,
        expectedResultPackageDate: 1546300800,
        acreageFloor: 50000000,
        scale: '20 tầng',
        buildingProjectType: {
            id: 5,
            text: 'Nhà Phố, Biệt Thự',
        },
        mainBuildingCategory: {
            id: 4,
            text: 'Xậy dựng móng và mặt bằng',
        },
        roleContractors: {
            id: 2,
            text: 'Chủ đầu tư',
        },
        roleHBC: {
            id: 2,
            text: 'Tổng thầu',
        },
        linkDocument: 'http://ndh.vn/su-kien-chung-khoan-dang-chu-y-ngay-6-4-2939769p146c155.news',
        presideHBC: {
            id: 11,
            text: 'Tổ  MEP Dự thầu ',
        },
        status: {
            id: 4,
            text: 'Nộp Lần 2',
        },
        progressMade: null,
        reasonWinPackage: '',
        reasonLostPackage: '',
        totalValue: 6000000000,
        // totalTime: 40000000,
        ratingProject: '1',
        // note: 'Xây dựng chính',
        startDateProject: 1548979200,
        endDateProject:  1556668799,
        totalTimeProject: 150000000,
        description: 'Trường học',
        phase: {
            parent: 'KẾT QUẢ DỰ THẦU',
            child: 'Trật thầu',
        }
    },
    {
        id: 6,
        nameProject: 'Dự án Alma Resort',
        codePackage: '105SB10',
        name: 'Xây dựng',
        task: 'Hợp tác thi công',
        address: '87 Nguyễn Chánh',
        zone: {
            id: 5,
            text: 'Nước ngoài',
        },
        quarterOfYear: {
            id: 4,
            text: 'Quý IV',
        },
        customer: {
            id: 1,
            text: 'Nguyễn Văn Linh',
        },
        customerType: {
            id: 2,
            text: 'Khách hàng cũ',
        },
        contact: {
            id: 4,
            text: 'Trưởng ban kiểm định: Hà Thị Một',
        },
        consultingUnit: 'CT CP đầu tư Việt',
        addressConsultingUnit: '10 Hùng Vương, Đà Lạt',
        phoneConsultingUnit: '012223548875',
        trackingeStartDate: 1541030400,
        submitPackageDate: 1543622400	,
        expectedResultPackageDate: 1546300800,
        acreageFloor: 40000000,
        scale: '40 tầng',
        buildingProjectType: {
            id: 6,
            text: 'Bệnh Viện',
        },
        mainBuildingCategory: {
            id: 3,
            text: 'Xậy dựng móng và mặt bằng',
        },
        roleContractors: {
            id: 2,
            text: 'Chủ đầu tư',
        },
        roleHBC: {
            id: 5,
            text: 'Thầu phụ',
        },
        linkDocument: 'http://ndh.vn/su-kien-chung-khoan-dang-chu-y-ngay-6-4-2939769p146c155.news',
        presideHBC: {
            id: 19,
            text: 'Lê Mạnh Duẩn',
        },
        status: {
            id: 4,
            text: 'Nộp Lần 5',
        },
        progressMade: null,
        reasonWinPackage: '',
        reasonLostPackage: '',
        totalValue: 5000000000,
        // totalTime: 40000000,
        ratingProject: '4',
        // note: 'Xây dựng chính',
        startDateProject: 1559347199,
        endDateProject:  1559347200,
        totalTimeProject: 200000000,
        description: 'Xây dựng sân bay',
        phase: {
            parent: 'HỒ SƠ DỰ THẦU',
            child: 'Chờ duyệt',
        }
    },
    {
        id: 7,
        nameProject: 'Khách sạn Biển Đông Phương',
        codePackage: '203CF12',
        name: 'Mua trang thiết bị',
        task: 'Giám sát thi công',
        address: '10 Âu Cơ',
        zone: {
            id: 4,
            text: 'Phú Quốc',
        },
        quarterOfYear: {
            id: 2,
            text: 'Quý II',
        },
        customer: {
            id: 3,
            text: 'Nguyễn Văn Linh',
        },
        customerType: {
            id: 1,
            text: 'Khách hàng mới',
        },
        contact: {
            id: 2,
            text: 'Trưởng ban kiểm định: Hà Thị Một',
        },
        consultingUnit: 'CTPA An Phát',
        addressConsultingUnit: '20 Quang Trung, tp Hồ Chí Minh',
        phoneConsultingUnit: '01697864213',
        trackingeStartDate: 1541030400,
        submitPackageDate: 1543622400	,
        expectedResultPackageDate: 1546300800,
        acreageFloor: 30000000,
        scale: '15 tầng',
        buildingProjectType: {
            id: 7,
            text: 'Hạ Tầng',
        },
        mainBuildingCategory: {
            id: 1,
            text: 'Xậy dựng móng và mặt bằng',
        },
        roleContractors: {
            id: 2,
            text: 'Chủ đầu tư',
        },
        roleHBC: {
            id: 3,
            text: 'Liên danh',
        },
        linkDocument: 'http://ndh.vn/su-kien-chung-khoan-dang-chu-y-ngay-6-4-2939769p146c155.news',
        presideHBC: {
            id: 23,
            text: 'Nguyễn Đức Trọng',
        },
        status: {
            id: 4,
            text: 'Nộp Lần 1',
        },
        progressMade: null,
        reasonWinPackage: '',
        reasonLostPackage: '',
        totalValue: 6000000000,
        // totalTime: 50000000,
        ratingProject: '3',
        // note: 'Giám sát thi công',
        startDateProject: 1577836800,
        endDateProject:  1577836800,
        totalTimeProject: 1583020800,
        description: 'Giám sát thi công',
        phase: {
            parent: 'HỒ SƠ DỰ THẦU',
            child: 'Đã gửi phân công tiến độ',
        }
    },
    {
        id: 8,
        nameProject: 'Dự an Riviera Point(quận 7)',
        codePackage: '152RP1',
        name: 'Xây dựng',
        task: 'Bao trì và xây dựng',
        address: '152 Nguyên Lương Bằng',
        zone: {
            id: 3,
            text: 'Miền Nam',
        },
        quarterOfYear: {
            id: 1,
            text: 'Quý I',
        },
        customer: {
            id: 1,
            text: 'Nguyễn Văn Linh',
        },
        customerType: {
            id: 2,
            text: 'Khách hàng cũ',
        },
        contact: {
            id: 1,
            text: 'Trưởng ban kiểm định: Hà Thị Một',
        },
        consultingUnit: 'CT CPTV TBS',
        addressConsultingUnit: '114 Phan Đăng Lưu, Tp.Hồ Chí Minh',
        phoneConsultingUnit: '01224500315',
        trackingeStartDate: 1531896837,
        submitPackageDate: 1534575237,
        expectedResultPackageDate: 1534748037,
        acreageFloor: 20000000,
        scale: '20 tầng',
        buildingProjectType: {
            id: 8,
            text: 'Nhà công nghiệp/ hạ tầng',
        },
        mainBuildingCategory: {
            id: 1,
            text: 'Xậy dựng móng và mặt bằng',
        },
        roleContractors: {
            id: 1,
            text: 'Chủ đầu tư',
        },
        roleHBC: {
            id: 1,
            text: 'Thầu chính',
        },
        linkDocument: 'http://www.hoabinhcorporation.com.vn/news/category/2-tin-cong-trinh.html',
        presideHBC: {
            id: 15,
            text: 'Đào Thị Lĩnh',
        },
        status: {
            id: 4,
            text: 'Nộp Lần 2',
        },
        progressMade: null,
        reasonWinPackage: '',
        reasonLostPackage: '',
        totalValue: 5000000000,
        // totalTime: 18000000,
        ratingProject: '5',
        // note: 'Dự án quạn trọng số 1',
        startDateProject: 1535612037,
        endDateProject: 1546152837,
        totalTimeProject: 16000000,
        description: 'Dự án thuộc công trình qui hoạch trong dự án qui hoạch của thành phố',
        phase: {
            parent: 'HỒ SƠ MỜI THẦU',
            child: 'Cần bổ sung HSMT',
        }
    },
    {
        id: 9,
        nameProject: 'Xây dựng công viên chấu Á, tp Đà Nẵng',
        codePackage: '653CV15',
        name: 'Mua trang thiết bị',
        task: 'Xây dựng bổ sung',
        address: '100 Đường 2/9, tp Đà Nẵng',
        zone: {
            id: 2,
            text: 'Miền Trung',
        },
        quarterOfYear: {
            id: 2,
            text: 'Quý II',
        },
        customer: {
            id: 3,
            text: 'Nguyễn Hòa',
        },
        customerType: {
            id: 2,
            text: 'Khách hàng cũ',
        },
        contact: {
            id: 1,
            text: 'Trưởng ban kiểm định: Hà Thị Một',
        },
        consultingUnit: 'CT CCDT QLH',
        addressConsultingUnit: '113, Thái Thị Bôn, tp Đà Nẵng',
        phoneConsultingUnit: '01226340487',
        trackingeStartDate: 1539912535,
        submitPackageDate: 1542590935,
        expectedResultPackageDate: 1542936535,
        acreageFloor: 50000000,
        scale: '20 tầng',
        buildingProjectType: {
            id: 1,
            text: 'Nhà hàng',
        },
        mainBuildingCategory: {
            id: 3,
            text: 'Xậy dựng móng và mặt bằng',
        },
        roleContractors: {
            id: 2,
            text: 'Chủ đầu tư',
        },
        roleHBC: {
            id: 3,
            text: 'Liên danh',
        },
        linkDocument: 'http://www.hoabinhcorporation.com.vn/news/9009-khoicongduantrungtamthuongmaiaeonmallhadong.html',
        presideHBC: {
            id: 9,
            text: 'TTTM',
        },
        status: {
            id: 4,
            text: 'Nộp Lần 1',
        },
        progressMade: null,
        reasonWinPackage: '',
        reasonLostPackage: '',
        totalValue: 8000000000,
        // totalTime: 25000000,
        ratingProject: '5',
        // note: 'Dự án cần phải thực hiện chính xác',
        startDateProject: 1545528535,
        endDateProject: 1549762135,
        totalTimeProject: 30000000,
        description: 'Dự án thuộc công trình thương mai chính của thành phố',
        phase: {
            parent: 'HỒ SƠ MỜI THẦU',
            child: 'Đã từ chối',
        }
    },
    {
        id: 10,
        nameProject: 'Xây dựng cầu Vượt Hòa Cầm, tp Đà Nẵng',
        codePackage: '986CVT10',
        name: 'Tư vấn xây dựng',
        task: 'Xây dựng chính',
        address: '100 Đường Tôn Đức Thắng, tp Đà Nẵng',
        zone: {
            id: 2,
            text: 'Miền Trung',
        },
        quarterOfYear: {
            id: 4,
            text: 'Quý IV',
        },
        customer: {
            id: 4,
            text: 'Nguyễn Hòa',
        },
        customerType: {
            id: 1,
            text: 'Khách hàng mới',
        },
        contact: {
            id: 1,
            text: 'Trưởng ban kiểm định: Hà Thị Một',
        },
        consultingUnit: 'CT CCDT QLH',
        addressConsultingUnit: '113, Thái Thị Bôn, tp Đà Nẵng',
        phoneConsultingUnit: '01226340487',
        trackingeStartDate: 1539912535,
        submitPackageDate: 1542590935,
        expectedResultPackageDate: 1542936535,
        acreageFloor: 20000000,
        scale: '20 tầng',
        buildingProjectType: {
            id: 10,
            text: 'Công trình nước ngoài',
        },
        mainBuildingCategory: {
            id: 2,
            text: 'Xậy dựng móng và mặt bằng',
        },
        roleContractors: {
            id: 4,
            text: 'Chủ đầu tư',
        },
        roleHBC: {
            id: 2,
            text: 'Tổng thầu',
        },
        linkDocument: 'http://www.hoabinhcorporation.com.vn/news/9009-khoicongduantrungtamthuongmaiaeonmallhadong.html',
        presideHBC: {
            id: 14,
            text: 'Lê Đình Biển',
        },
        status: {
            id: 4,
            text: 'Nộp Lần 1',
        },
        progressMade: null,
        reasonWinPackage: '',
        reasonLostPackage: '',
        totalValue: 8000000000,
        // totalTime: 25000000,
        ratingProject: '5',
        // note: 'Dự án cần phải thực hiện chính xác',
        startDateProject: 1545528535,
        endDateProject: 1549762135,
        totalTimeProject: 30000000,
        description: 'Dự án thuộc công trình thương mai chính của thành phố',
        phase: {
            parent: 'HỒ SƠ MỜI THẦU',
            child: 'Đã từ chối',
        }
    },
    {
        id: 11,
        nameProject: 'Trung tâm Thương mại AEON Mall Hà Đông',
        codePackage: '320HĐ',
        name: 'Hỗ trợ công trình',
        task: 'Xây dựng mới',
        address: '75 Hồ Tùng Mậu',
        zone: {
            id: 1,
            text: 'Miền Bắc',
        },
        quarterOfYear: {
            id: 3,
            text: 'Quý III',
        },
        customer: {
            id: 3,
            text: 'Nguyễn Hòa',
        },
        customerType: {
            id: 1,
            text: 'Khách hàng mới',
        },
        contact: {
            id: 4,
            text: 'Trưởng ban kiểm định: Hà Thị Một',
        },
        consultingUnit: 'CT CCDT QLH',
        addressConsultingUnit: '105 Thái Bình, Dương Nội',
        phoneConsultingUnit: '01226340487',
        trackingeStartDate: 1539912535,
        submitPackageDate: 1542590935,
        expectedResultPackageDate: 1542936535,
        acreageFloor: 20000000,
        scale: '20 tầng',
        buildingProjectType: {
            id: 11,
            text: 'Nhà mẫu',
        },
        mainBuildingCategory: {
            id: 2,
            text: 'Xậy dựng móng và mặt bằng',
        },
        roleContractors: {
            id: 1,
            text: 'Chủ đầu tư',
        },
        roleHBC: {
            id: 4,
            text: 'Thầu D&B',
        },
        linkDocument: 'http://www.hoabinhcorporation.com.vn/news/9009-khoicongduantrungtamthuongmaiaeonmallhadong.html',
        presideHBC: {
            id: 20,
            text: 'Công trường',
        },
        status: {
            id: 4,
            text: 'Nộp Lần 5',
        },
        progressMade: null,
        reasonWinPackage: '',
        reasonLostPackage: '',
        totalValue: 8000000000,
        // totalTime: 25000000,
        ratingProject: '5',
        // note: 'Dự án cần phải thực hiện chính xác',
        startDateProject: 1545528535,
        endDateProject: 1549762135,
        totalTimeProject: 30000000,
        description: 'Dự án thuộc công trình thương mai chính của thành phố',
        phase: {
            parent: 'HỒ SƠ DỰ THẦU',
            child: 'Đã xác địnhh phân công',
        }
    }
];
